name: Style

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Install format dependencies
        run: |
          brew install clang-format
          pip3 install cmake_format==0.6.11 pyyaml

      - name: install GCC 11
        run: |
          sudo apt update
          sudo apt install gcc-11 g++-11

      - name: configure
        run: cmake -Stest -Bbuild
        env:
          CC: gcc-11
          CXX: g++-11

      - name: check style
        run: cmake --build build --target check-format
        env:
          CC: gcc-11
          CXX: g++-11
